[package]
name = "abc444-c-20260217_0807"
edition = "2021"

[[bin]]
name = "abc444-c-20260217_0807"
path = "main.rs"

[dependencies]
proconio.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
ac-lib.workspace = true
