[package]
name = "abc445-c-20260215_1430"
edition = "2021"

[[bin]]
name = "abc445-c-20260215_1430"
path = "main.rs"

[dependencies]
proconio.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
ac-lib.workspace = true
