[package]
name = "abc445-e-20260215_2307"
edition = "2021"

[[bin]]
name = "abc445-e-20260215_2307"
path = "main.rs"

[dependencies]
proconio.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
ac-lib.workspace = true
