[package]
name = "abc445-a-20260215_1346"
edition = "2021"

[[bin]]
name = "abc445-a-20260215_1346"
path = "main.rs"

[dependencies]
proconio.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
ac-lib.workspace = true
