[package]
name = "abc444-a-20260217_0751"
edition = "2021"

[[bin]]
name = "abc444-a-20260217_0751"
path = "main.rs"

[dependencies]
proconio.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
ac-lib.workspace = true
