[package]
name = "abc445-d-20260215_2034"
edition = "2021"

[[bin]]
name = "abc445-d-20260215_2034"
path = "main.rs"

[dependencies]
proconio.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
ac-lib.workspace = true
