[package]
name = "abc444-d-20260220_0007"
edition = "2021"

[[bin]]
name = "abc444-d-20260220_0007"
path = "main.rs"

[dependencies]
proconio.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
ac-lib.workspace = true
